apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpi-back
  labels:
    app: kpi-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kpi-back
  template:
    metadata:
      labels:
        app: kpi-back
    spec:
      containers:
        - name: kpi-be
          image: '@sha256:'
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Xmx512m -Xms256m"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-external-secret
                  key: db-host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-external-secret
                  key: db-name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-external-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-external-secret
                  key: db-password
